project_id = "silkjqepcbhlflbdtvgg"

[functions.send-password-reset]
verify_jwt = false

[functions.verify-reset-token]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = false

[functions.suta-chat]
verify_jwt = false

[functions.send-auth-otp]
verify_jwt = false

[functions.verify-auth-otp]
verify_jwt = false

[functions.send-sms-hybrid]
verify_jwt = false

[functions.send-sms-brevo]
verify_jwt = false

[functions.send-whatsapp-hybrid]
verify_jwt = false

[functions.send-whatsapp-otp]
verify_jwt = false

[functions.send-whatsapp-brevo]
verify_jwt = false

[functions.intouch-sms]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-lease-notifications]
verify_jwt = false

[functions.check-lease-expirations]
verify_jwt = false

[functions.send-application-notifications]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-mandate-notifications]
verify_jwt = false

[functions.hello-world]
enabled = true
verify_jwt = true
import_map = "./functions/hello-world/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hello-world/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hello-world/*.html" ]
